### ISSUE TITLE
Populate database to enter a pin and have a basic setup

### ISSUE THREAD

**Issue by delkant** [Richwb-zz/Restaurant-PoS#90]
Can you please provide more documentation on how populate the database and have it running?. 

Thanks!

**Comment by josueruiz7** [comment]
I have the same problem, any news?

**Comment by josueruiz7** [comment]
I am getting this in the log:

"> restaurant-pos@0.0.0 client /home/ec2-user/Restaurant-PoS
[1] > node ./scripts/start-client.js
[1]
[1]
[1] > client@0.1.0 start /home/ec2-user/Restaurant-PoS/client
[1] > react-scripts start
[1]
[1] /home/ec2-user/Restaurant-PoS/client/node_modules/react-scripts/scripts/star                                                                                        t.js:31
[1] const {
[1]       ^
[1]
[1] SyntaxError: Unexpected token {
[1]     at exports.runInThisContext (vm.js:53:16)
[1]     at Module._compile (module.js:373:25)
[1]     at Object.Module._extensions..js (module.js:416:10)
[1]     at Module.load (module.js:343:32)
[1]     at Function.Module._load (module.js:300:12)
[1]     at Function.Module.runMain (module.js:441:10)
[1]     at startup (node.js:139:18)
[1]     at node.js:968:3
[1]
[1] npm ERR! Linux 4.14.62-70.117.amzn2.x86_64
[1] npm ERR! argv ""/home/ec2-user/.nvm/versions/node/v4.4.5/bin/node"" ""/home/ec2                                                                                        -user/.nvm/versions/node/v4.4.5/bin/npm"" ""start""
[1] npm ERR! node v4.4.5
[1] npm ERR! npm  v2.15.5
[1] npm ERR! code ELIFECYCLE
"

**Comment by dylanOshima** [comment]
I was able to get it working! To anyone who might want to use this, the steps I followed:

1. Installed MongoDB on my Mac (using homebrew)
2. Run MongoDB
3. Run `npm start` in the main directory
4. I had to send a POST request (I used Postman) to `http://localhost:4444/servers/add` with a new server as the body. The information you need to provide (in JSON format) is: `name` and `code`. 
5. Then I was able to login

It's a bit convoluted. Also @josueruiz7 I'm not quite sure what that error is. I'm working to try and improve from this repo and will keep whoever's interested updated.
